site_name: rapidPF documentation
site_url: https://kit-iai.github.io/rapidPF/
site_description: Documentation for rapidPF
site_author: Tillmann Mühlpfordt
docs_dir: docs/

repo_url: https://github.com/KIT-IAI/rapidPF
   
theme:
    name: material
    navigation_depth: 2

extra_css:
    - 'css/extra.css'

markdown_extensions:
    - pymdownx.arithmatex
    - smarty
    - tables
    - toc
    - admonition
    - codehilite:
        linenums: True
    

plugins:
    - search
    - awesome-pages:
        collapse_single_pages: true

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

